### ISSUE TITLE
formula for brew install docker-engine ?

### ISSUE THREAD

**Issue by timotheecour** [sjackman/docker-linuxbrew#5]
installing docker on mac (including all that's required to start a daemon and run) is dead simple and supported via homebrew. On ubuntu, there are many steps involved which is counterintuitive since docker runs on linux, not mac. Is there any plan to have a linuxbrew formula for installing the remaining dependencies to be able to run a damon and containers ?

https://github.com/sjackman/docker-linuxbrew/issues/4 suggests 'yum install docker-engine' but it's centos specific

**Comment by sjackman** [comment]
`brew install docker` works to install the Docker client on Linuxbrew. There's no plans for a `docker-engine` formula for Linuxbrew, but a pull request would be welcome.

**Comment by timotheecour** [comment]
NOTE: this worked on ubuntu 16.04

```
brew install docker docker-machine
sudo apt-get install virtualbox
docker-machine create --driver virtualbox default
eval "$(docker-machine env default)"
docker run hello-world
```

**Comment by timotheecour** [comment]
EDIT: using `docker-machine` adds a level of virtualization and may not be a perfect workaround (eg, not sure how to connect to a port exposed by a docker container to other machines when using dcoker-machine)

@sjackman would you have any idea for a starting point to get a linuxbrew formula for docker-engine? asking there https://github.com/docker/docker/issues/26388 didn't help

**Comment by sjackman** [comment]
Because Docker Engine requires root access and is a daemon, I'm not sure that it's a good fit for Linuxbrew. Here's Docker's installation instructions:
https://docs.docker.com/engine/installation/#/on-linux

There's binary tarballs here:
https://github.com/docker/docker/releases
and instructions https://docs.docker.com/engine/installation/binaries/
