### ISSUE TITLE
python-setuptools is not preinstalled

### ISSUE THREAD

**Issue by bw-yuhogg** [sjackman/docker-linuxbrew#8]
None of the Dockerfiles specify an installation of `python-setuptools`. This leads to, for example, `scons` failing to build because `/usr/bin/python` is unavailable.

```
BuildError: Failed executing: /usr/bin/python setup.py install --prefix=/home/linuxbrew/.linuxbrew/Cellar/scons/2.5.0 --standalone-lib --install-lib=/home/linuxbrew/.linuxbrew/Cellar/scons/2.5.0/libexec/scons-local --install-scripts=/home/linuxbrew/.linuxbrew/Cellar/scons/2.5.0/bin --install-data=/home/linuxbrew/.linuxbrew/Cellar/scons/2.5.0/libexec --no-version-script --no-install-man
```

My apologies if this is intentional, for example as a trap to catch missing Python dependencies in formulae.

**Comment by sjackman** [comment]
This repository is kaput. This Dockerfile is superseded by https://github.com/Linuxbrew/brew/blob/master/Dockerfile
It probably should install `python-setuptools`. I do want to keep the image as small as reasonably possible though, while still behaving as expected. If `python` is already installed, then also installing `python-setuptools` is the right thing to do.
