### ISSUE TITLE
Possible to create minimised docker images?

### ISSUE THREAD

**Issue by michaelbarton** [sjackman/docker-linuxbrew#9]
I am unfamiliar with linuxbrew and how it installs packages. In general docker images can be larger than they need to be if the tools needed to build software are left in any of the file system layers. For example I believe it's considered good practice to build all software in a single layer, then remove build tools in the same layer so they never appear in the final image.

Would it be possible to have an even-more-minimal linuxbrew image so that I could take advantage of linuxbrew to install the software I want, without distributing images that have ruby, gcc and so forth? For example perhaps in a single file system layer install linuxbrew, install the package then strip out all the build tools?

**Comment by sjackman** [comment]
The current Linuxbrew Docker image is meant to provide a fairly feature complete version of Linuxbrew, including Ruby and development tools. I can definitely see a good argument for providing a minimal Linuxbrew Docker image. If the tool being installed and its dependencies are installed from precompiled binary bottles, there's no need for `gcc` ever to be installed at all.

I'm short on time at the moment, but I like this idea. Would you like to take a stab at it? The canonical Dockerfile for Linuxbrew is at
https://github.com/Linuxbrew/brew/blob/master/Dockerfile

**Comment by michaelbarton** [comment]
Thanks for you quick response Shaun. I did a quick test install of spades and
the following brews were installed:

patchelf, homebrew/dupes/ncurses, readline, sqlite, gdbm, zlib, openssl,
bzip2, python, gmp, mpfr, libmpc, isl, gcc

If you would like to contrast this with bioboxes/spades I created:

https://github.com/bioboxes/spades/blob/master/image/bin/install.sh

By keeping only the essential packages the image size is ~192MB. I would like
to use linuxbrew in bioboxes as I think it is better to not reinvent the
wheel. However it seems like the feature-complete requirements for linuxbrew
you mentioned, and the small image sizes I would like for bioboxes means these
might be going in two different directions.

I'm not sure if it might be possible to create minimal recipes of each
homebrew, e.g. spades-minimal that spades would depend on, but this might be a
lot work with only little gain.

**Comment by sjackman** [comment]
`spades` shouldn't pull in `gcc` as a dependency if it and all of its dependencies are bottled.
Two tips:
1. Use Ubuntu 14 as the base image
2. Install Linuxbrew in `/home/linuxbrew/.linuxbrew` to use non-relocatable bottles

**Comment by michaelbarton** [comment]
Thanks Shaun. I see my mistake here. I did a bit more reading into bottles and
I understand that these are the binary compiled packages. In the spades package
I see that there is a `:x86_64_linux` bottle:

https://github.com/Homebrew/homebrew-science/blob/master/spades.rb

I'm currently creating bioboxes in a Debian Docker image because the image size
is 65MB smaller than Ubuntu. However if compiled bottles could be installed
into Alpine Linux this could create some very small final image sizes.

```
alpine:3.3      4.7 MB
debian:jessie   123 MB
ubuntu:14.04    188 MB
```

Do you think it would be possible to do this? Could linux brew be overritten to
installed the bottle even if it is not Ubuntu 14?

**Comment by sjackman** [comment]
Linuxbrew bottles can be used on any Linux distribution released in the last ten years or so. If the distribution provides glibc 2.19 or better you're good to go. If the distribution provides glibc < 2.19, Linuxbrew will install glibc for `libc.so.6` and gcc for `libstdc++.so.6` the first time that a bottle is installed.

Be sure to install Linuxbrew in `/home/linuxbrew/.linuxbrew`, or compiling non-relocatable bottles from source will require `gcc`.

**Comment by michaelbarton** [comment]
I've installed glibc 2.23 on alpine:3.3 and patched this file:

```
diff --git a/Library/Homebrew/requirements/glibc_requirement.rb b/Library/Homebrew/requirements/glibc_requirement.rb
index 279aa0c..02a4e73 100644
--- a/Library/Homebrew/requirements/glibc_requirement.rb
+++ b/Library/Homebrew/requirements/glibc_requirement.rb
@@ -13,7 +13,7 @@ class GlibcRequirement < Requirement

   def self.system_version
     return @@system_version if @@system_version
-    libc = ["/lib/x86_64-linux-gnu/libc.so.6", "/lib64/libc.so.6", "/lib/libc.so.6", "/lib/i386-linux-gnu/libc.so.6", "/lib/arm-linux-gnueabihf/libc.so.6"].find do |s|
+    libc = ["/usr/glibc-compat/lib/libc.so.6"].find do |s|
       Pathname.new(s).executable?
     end
     raise "Unable to locate the system's glibc" unless libc
```

`brew doctor` returns:

Warning: No developer tools installed.
Install Clang or brew install gcc

I then run the following command:

```
brew install \
  https://raw.githubusercontent.com/Homebrew/homebrew-science/master/spades.rb \
  --bottle-arch=x86_64_linux
```

However homebrew still tries to install gcc and clang. Could you offer any
further suggestions?

**Comment by sjackman** [comment]
I've always considered the cost of the base image as a sunk cost, since ubuntu is such a common base image, there's a good chance that the user already has it pulled. Based on this blog post, `ubuntu` is the most popular base image: https://www.brianchristner.io/docker-image-base-os-size-comparison/

Does it work as expected for you using Ubuntu as the base image? If so, we can start troubleshooting why Alpine doesn't work as expected.

**Comment by sjackman** [comment]
> Alpine Linux is a Linux distribution based on musl and BusyBox

I think you'll find that a number of bioinformatics applications will break without glibc and GNU coreutils. I'm not sure it's worth the effort to troubleshoot the issues that will arise from starting with such an unusual base system. I'll help where I can if you want to put in the effort.

You could start with the alpine base image and install the typical essential dependencies like glibc and coreutils using brew.

**Comment by sjackman** [comment]
Please report the output of
```
brew config
brew install hello
brew gist-logs hello
```

**Comment by michaelbarton** [comment]
Thanks for taking the time follow Shaun. I think an ideal end goal would be
alpine because combined with linuxbrew bottles it could create very small
images. There is an alpine package `glibc-2.23-r3.apk` that does install glibc.

I agree that trying ubuntu first is a good start though as debugging alipine
could be painstaking. I tried this on the linuxbrew-core image and I got the
following output:

```
docker run -it sjackman/linuxbrew-core /bin/bash
linuxbrew@161089f7cbe0:~$ brew install homebrew/master/spades --bottle-arch=x86_64_linux
==> Auto-updated Homebrew!
Updated Homebrew from 92d76c2 to 4d6f074.
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Tapping homebrew/master
Cloning into '/home/linuxbrew/.linuxbrew/Library/Taps/homebrew/homebrew-master'...
Username for 'https://github.com':
```

It appears to be asking for a github password.

**Comment by sjackman** [comment]
I fixed the logic that locates `libc.so.6` for Alpine Linux.

I've created instructions to install Linuxbrew on Alpine Linux.
https://github.com/Linuxbrew/brew/wiki/Alpine-Linux

**Comment by sjackman** [comment]
The Linuxbrew installation on Alpine Linux works now.

```
$ brew install hello
==> Installing dependencies for hello: patchelf, zlib, binutils, linux-headers, glibc, xz, gmp, gpatch, mpfr, libmpc, isl, gcc
…
==> Installing hello
==> Downloading https://linuxbrew.bintray.com/bottles/hello-2.10.x86_64_linux.bo
######################################################################## 100.0%
==> Pouring hello-2.10.x86_64_linux.bottle.tar.gz
🍺  /home/linuxbrew/.linuxbrew/Cellar/hello/2.10: 52 files, 595.4K
```

`glibc` is needed because Alpine Linux includes `musl` rather than `glibc`, and the Linuxbrew bottles are built against `glibc` 2.19.

`gcc` is needed because it provides `libgcc_s.so.1` and `libstdc++.so.6`. Installing `gcc` pulls in its dependencies `binutils, gmp, mpfr, libmpc, isl`.

The sizes of the installed bottles, sorted by size:

```
336.0K  gpatch/2.7.5
420.0K  zlib/1.2.8
488.0K  libmpc/1.0.3
1.2M    patchelf/0.9_1
1.9M    xz/5.2.2
3.6M    gmp/6.1.1
3.9M    mpfr/3.1.4
4.7M    isl/0.15
5.3M    linux-headers/3.18.27
36.8M   glibc/2.19
203.2M  binutils/2.27
255.8M  gcc/5.3.0
517.6M  total
```

**Comment by sjackman** [comment]
In https://github.com/Linuxbrew/brew/issues/83 "Is gcc required if you plan to only install bottles (pre-built bins)?" @staticfloat asked whether `gcc` was a necessary dependency, and suggested creating a `libstdc++` formula/bottle.

To experiment, it wouldn't be too difficult to extract from the `gcc` bottle only the library files.

```
gcc/5.3.0/lib/libgcc_s.so.1
gcc/5.3.0/lib/libstdc++.so.6
gcc/5.3.0/lib/libstdc++.so.6.0.21
```

**Comment by sjackman** [comment]
For formula that have no actual dependency on neither `libgcc_s.so.1` nor `libstdc++.so.6`, you can remove the unnecessary dependencies that were installed. With samtools for example:

```
❯❯❯ patchelf --print-needed ~/.linuxbrew/bin/samtools
libhts.so.1
libncursesw.so.6
libm.so.6
libz.so.1
libpthread.so.0
libc.so.6
❯❯❯ ldd ~/.linuxbrew/bin/samtools
    linux-vdso.so.1 (0x00007ffc42386000)
    libhts.so.1 => /home/linuxbrew/.linuxbrew/lib/libhts.so.1 (0x00007f2606655000)
    libncursesw.so.6 => /home/linuxbrew/.linuxbrew/lib/libncursesw.so.6 (0x00007f26063fd000)
    libm.so.6 => /home/linuxbrew/.linuxbrew/lib/libm.so.6 (0x00007f260610d000)
    libz.so.1 => /home/linuxbrew/.linuxbrew/lib/libz.so.1 (0x00007f2605ef9000)
    libpthread.so.0 => /home/linuxbrew/.linuxbrew/lib/libpthread.so.0 (0x00007f2605cdd000)
    libc.so.6 => /home/linuxbrew/.linuxbrew/lib/libc.so.6 (0x00007f2605965000)
    /home/linuxbrew/.linuxbrew/lib/ld.so (0x00007f26068ec000)
```

```
❯❯❯ brew install samtools
❯❯❯ brew remove binutils gcc gmp gpatch isl libmpc linux-headers mpfr patchelf xz
❯❯❯ brew list
glibc     htslib    ncurses   samtools  zlib
❯❯❯ du -csh */*
36.8M   glibc/2.19
17.2M   htslib/1.3.1
20.4M   ncurses/6.0_2
1.1M    samtools/1.3.1
420.0K  zlib/1.2.8
75.9M   total
❯❯❯ samtools --version
samtools 1.3.1
Using htslib 1.3.1
Copyright (C) 2016 Genome Research Ltd.
```

**Comment by sjackman** [comment]
```
❯❯❯ brew linkage samtools
Homebrew libraries:
  /home/sjackman/.linuxbrew/lib/libc.so.6 (glibc)
  /home/sjackman/.linuxbrew/lib/libm.so.6 (glibc)
  /home/sjackman/.linuxbrew/lib/libpthread.so.0 (glibc)
  /home/sjackman/.linuxbrew/lib/libncursesw.so.6 (homebrew/dupes/ncurses)
  /home/sjackman/.linuxbrew/lib/libhts.so.1 (homebrew/science/htslib)
  /home/sjackman/.linuxbrew/lib/libz.so.1 (zlib)
Possible undeclared dependencies:
  zlib
```

~~Once I merge https://github.com/Linuxbrew/brew/pull/115, which implements `brew linkage` for Linuxbrew.~~ Done.

**Comment by michaelbarton** [comment]
Thanks for all your effort Shaun, that's fantastic. I'm going to create some fastq proprocessor bioboxes in the next couple of weeks. I'll trying using linuxbrew on alpine for this. I'll create homebrew science recipes where necessary.

**Comment by sjackman** [comment]
Great! I'll close this issue now. Feel free to open a new issue if you have further questions.

**Comment by andreyantipov** [comment]
Hello @sjackman could you please help with me one moment: How i can ```brew install hello``` if ldd utility works through musl and package libc6-compat doesn't provide any binaries? As i understand - before install linuxbrew gcc i need to get somewhere and install ldd which works with glibc, right?

**ldd**
```bash
musl libc (x86_64)
Version 1.1.16
Dynamic Program Loader
Usage: ldd [options] [--] pathname
```


**apk info -L libc6-compat**
```bash
libc6-compat-1.1.16-r13 contains:
lib/libm.so.6
lib/libc.so.6
lib/libcrypt.so.1
lib/ld-linux-x86-64.so.2
lib/librt.so.1
lib/libutil.so.1
lib/libpthread.so.0
lib64
```

**brew install hello**
```bash
Updating Homebrew...
==> Installing dependencies for hello: bzip2, zlib, binutils, linux-headers, glibc, xz, m4, gmp, mpfr, libmpc, isl, gcc
==> Installing hello dependency: bzip2
==> Downloading https://linuxbrew.bintray.com/bottles/bzip2-1.0.6_1.x86_64_linux.bottle.tar.gz
Already downloaded: /home/me/.cache/Homebrew/bzip2-1.0.6_1.x86_64_linux.bottle.tar.gz
==> Pouring bzip2-1.0.6_1.x86_64_linux.bottle.tar.gz
Error: Failure while executing: ldd /home/me/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bunzip2
	/home/me/.linuxbrew/lib/ld.so (0x5605eaa5a000)

	libc.so.6 => /home/me/.linuxbrew/lib/ld.so (0x5605eaa5a000)

Error relocating /home/me/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bunzip2: __strcat_chk: symbol not found

Error relocating /home/me/.linuxbrew/Cellar/bzip2/1.0.6_1/bin/bunzip2: __fprintf_chk: symbol not found
 
Warning: Bottle installation failed: building from source.
==> Downloading http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz
Already downloaded: /home/me/.cache/Homebrew/bzip2-1.0.6.tar.gz
==> make install PREFIX=/home/me/.linuxbrew/Cellar/bzip2/1.0.6_1
Last 15 lines from /home/me/.cache/Homebrew/Logs/bzip2/01.make:
2017-09-20 15:40:04 +0000

make
install
PREFIX=/home/me/.linuxbrew/Cellar/bzip2/1.0.6_1
```

**Comment by sjackman** [comment]
I can replicate this issue. Here's an upstream issue: https://github.com/gliderlabs/docker-alpine/issues/149
where they say that the issue should be reported to https://github.com/sgerrand/alpine-pkg-glibc
The following workaround worked for me:
```sh
brew install --ignore-dependencies patchelf glibc
brew install binutils linux-headers gcc
```
After that `brew install hello` works. `brew install -s hello` currently fails with
```
/home/linuxbrew/.linuxbrew/bin/ld: cannot find crt1.o: No such file or directory
/home/linuxbrew/.linuxbrew/bin/ld: cannot find crti.o: No such file or directory
```
I can fix that. As a temporary workaround `brew install --env=std -s hello` does work.

I'm building a Docker image now…
```sh
docker run -it linuxbrew/alpine
```

**Comment by sjackman** [comment]
This repo `sjackman/docker-linuxbrew` is defunct. Check out https://github.com/Linuxbrew/docker

**Comment by sjackman** [comment]
@michaelbarton I've created a Docker image for Linuxbrew on Alpine Linux:
```sh
docker run -it linuxbrew/alpine
```
https://github.com/Linuxbrew/docker/blob/master/alpine/Dockerfile
To install a compiler, use…
```sh
brew install binutils linux-headers gcc
```
or possibly (untested)
```sh
sudo apk install g++
```

**Comment by michaelbarton** [comment]
Thanks Shaun. I think this would be a great use case for multi stage
builds with Docker. You could fetch and install packages in the
linuxbrew package and then copy over only the required files to an
even more minimal alpine image or possibly even google's distroless
containers

https://github.com/GoogleCloudPlatform/distroless

**Comment by sjackman** [comment]
I just learned about multi-stage builds a few days ago. Once Linuxbrew were bootstrapped with Alpine Linux, I could throw away Alpine Linux.

**Comment by michaelbarton** [comment]
Yes, or you wouldn't even necessarily need to use Alpine anymore
either. You could use a full debian image and then use a distroless
image to run the software.

**Comment by andreyantipov** [comment]
@sjackman Thanks Shaun! I'm going to try it now with my brew bundle pkg list
